name: firt-workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
     - name: To greet
       run: echo "Hello welcome"
     - name: To give background
       run: |
         echo "Hello your KT is started"
         echo "please ask if you have any doubts"
     - name: Target date 
        run: echo "complete in 1 month"
