name: CI-workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: clonning repo
        run: echo "clonning repo"
      - name: install plugins
        run: |
          echo "cleaning"
          echo "brooming"
