name: firt-workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
     - name: to greet
       run: echo "Hello welcome"
     - name: to give background
       run: echo "Hello your KT is started"
